# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=True, upload_to='headportrait', verbose_name='头像'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='it_user',
        ),
    ]
