# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181224_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='static/image/head.jpg', verbose_name='头像路径'),
        ),
    ]
