# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/image/head.jpg', upload_to='head', verbose_name='头像路径'),
        ),
    ]
