# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='帖子名称')),
                ('desc', models.CharField(max_length=20, verbose_name='下载方式')),
                ('unite', models.CharField(max_length=20, verbose_name='资源大小')),
                ('image', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('all_status', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否全套')),
                ('merber_status', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否需要会员')),
            ],
            options={
                'verbose_name_plural': '帖子',
                'db_table': 'it_card',
                'verbose_name': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Card_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='资源类型')),
                ('image', models.ImageField(default=None, upload_to='type', verbose_name='商品类型图片')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=200, verbose_name='帖子评论')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexGardsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
            ],
            options={
                'verbose_name_plural': '首页轮播商品',
                'db_table': 'it_index_banner',
                'verbose_name': '首页轮播商品',
            },
        ),
    ]
