# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20181222_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card_Type', verbose_name='帖子类型_id'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帖子发表人_id'),
        ),
    ]
