# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20181222_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='unite',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
