# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-23 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20181222_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=30, verbose_name='新闻名字')),
                ('url', models.CharField(max_length=100, verbose_name='新闻地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='新闻类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='way',
            field=models.CharField(default='百度网盘', max_length=20, verbose_name='下载方式'),
        ),
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, verbose_name='帖子详情'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card_Type', verbose_name='帖子类型'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帖子发表人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人_id'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.News_Type', verbose_name='新闻类型'),
        ),
    ]
