# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-23 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20181223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='way',
            field=models.CharField(max_length=20, verbose_name='下载方式'),
        ),
    ]
