# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20181223_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='news_type',
            options={'verbose_name': '新闻类型', 'verbose_name_plural': '新闻类型'},
        ),
        migrations.AlterField(
            model_name='card_type',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='type', verbose_name='商品类型图片'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='it_news',
        ),
        migrations.AlterModelTable(
            name='news_type',
            table='it_news_type',
        ),
    ]
