# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_remove_card_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card.Card', verbose_name='帖子_id'),
        ),
    ]
