# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-30 15:14
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_comment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='帖子详情'),
        ),
    ]
