# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20181230_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(upload_to='./media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
