# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_blogadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAdmin',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_type_id',
        ),
        migrations.AddField(
            model_name='card',
            name='imge',
            field=models.ImageField(null=True, upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card_Type', verbose_name='帖子类型'), verbose_name='详情图片'),
        ),
        migrations.AlterField(
            model_name='indexgardsbanner',
            name='image',
            field=models.ImageField(upload_to='type', verbose_name='图片'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='News_Type',
        ),
    ]
