# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20190111_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='imge',
        ),
    ]
