# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_remove_card_imge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, verbose_name='帖子名称'),
        ),
    ]
